#!/bin/bash
#PBS -N smilei_tuto_Rad_MC
#PBS -l select=1:ncpus=8:mem=4gb:scratch_local=400mb
#PBS -l walltime=02:00:00

trap 'clean_scratch' TERM EXIT # nastaveni uklidu SCRATCHE v pripade chyby

cd $SCRATCHDIR || exit 1 # vstoupi do scratch adresare

module purge
module add boost/1.79.0-gcc-10.2.1-4pgmuar
module add fftw/3.3.10-gcc-10.2.1-yxsjm6z hdf5/1.12.2-gcc-10.2.1-gfdwqr3
module add gettext/0.20.2-gcc

export HDF5_ROOT_DIR=/cvmfs/software.metacentrum.cz/spack18/software/linux-debian11-x86_64_v2/gcc-10.2.1/hdf5-1.12.2-gfdwqr3fdxejqi4ykiv7ammx4cmxmm7c/
export BOOST_ROOT_DIR=/cvmfs/software.metacentrum.cz/spack18/software/linux-debian11-x86_64_v2/gcc-10.2.1/boost-1.79.0-4pgmuar4icgafmrdpfn6pqmhidbtrnhy/
module list

cd /storage/brno2/home/jvabek/Smilei_tutos/SR/Radiation_Monte_Carlo
date
mpirun -n 8 /storage/brno2/home/jvabek/git/Smilei_test/smilei /storage/brno2/home/jvabek/Smilei_tutos/SR/Radiation_Monte_Carlo/tst2d_electron_laser_collision.py
date
